- name: Assign users to their team with the 'Member' role
  ansible.controller.role:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_admin_user }}"
    controller_password: "{{ controller_admin_password }}"
    validate_certs: false
    user: "{{ item.username }}"
    team: "{{ item.team }}"
    role: "member"
    state: present
  loop: "{{ users }}"
  when: item.team is defined

- name: Assign special roles to teams
  ansible.controller.role:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_admin_user }}"
    controller_password: "{{ controller_admin_password }}"
    validate_certs: false
    team: "{{ item.name }}"
    role: "{{ item.roles[0].role }}"  # Get the role from the first item in the list
    organization: "{{ item.organization }}"
    state: present
  loop: "{{ teams }}"
  when: item.roles is defined  # Only run this task for teams that have a 'roles' list
